services:
  backend:
    build:
      context: ./backend
    volumes:
      - hf_cache:/app/cache/huggingface
    environment:
      - HF_HOME=/app/cache/huggingface
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ports:
      - "8000:8000"
    restart: always

volumes:
  hf_cache:
